spring:
  application:
   name: SpringProfiles
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp
   
server:
  port: 2000
  servlet:
   context-path: /mvc
   
message: This is default user

# ---
# Must include for JSP pages
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp

# Custom port and context-path are a good practice
# server.port=2000
# server.servlet.context-path=/mvc

# custom message retrieved by the controller program to pass to view page using @Value
# message=This is default user
# ---
