# The default configuration will have the general configurations
# The environment specific configurations will be separated by `---` separator
# We can as many custom configurations as we want in a single application.yml

# Default Configuration

spring:
  application:
    name: SpringBootMVC
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: dev

server:
  port: 3000
  servlet:
    context-path: /mvc

logging:
  level:
    web: DEBUG

message: Welcome default user

---
# Development Environment Configuration

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 2000

message: Welcome Development user

---
# Production Environment Configuration

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 4000

message: Welcome production user